packages:
  - "packages/*"
  - "modules/*"
  - "modules/*/playground"
catalog:
  '@nuxt/eslint': ^1.15.2
  '@nuxt/ui': ^4.6.1
  '@oxlint/plugins': latest
  '@typescript-eslint/parser': ^8.60.1
  '@typescript-eslint/rule-tester': ^8.60.1
  '@typescript-eslint/utils': ^8.60.1
  '@types/node': latest
  '@vueuse/core': ^14.2.1
  eslint: ^10.4.1
  nuxt: ^4.4.7
  tailwindcss: ^4.0.0
  tsdown: latest
  typescript: ~6.0.3
  vitest: ^4.1.8
  vue-eslint-parser: ^10.4.1
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
