packages:
  - 'packages/*'
  - 'modules/*'
  - 'modules/*/playground'
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sqlite3: true
  unrs-resolver: true
  vue-demi: true
overrides:
  '@nustackjs/lint-plugin-nuxt': workspace:*
  '@nustackjs/lint-plugin-nuxt-ecosystem': workspace:*
  '@nustackjs/lint-plugin-vite': workspace:*
  '@nustackjs/lint-plugin-vueuse': workspace:*
catalogs:
  build:
    '@nuxt/module-builder': ^1.0.2
    tsdown: ^0.22.3
    unbuild: ^3.6.1
  eslint:
    '@antfu/eslint-config': ^9.1.0
    '@eslint/config-inspector': ^3.0.4
    '@nuxt/eslint': ^1.16.0
    '@nuxt/eslint-config': ^1.16.0
    '@oxlint/plugins': ^1.72.0
    '@typescript-eslint/parser': ^8.62.1
    '@typescript-eslint/rule-tester': ^8.62.1
    '@typescript-eslint/utils': ^8.62.1
    eslint: ^10.6.0
    eslint-flat-config-utils: ^3.2.0
    eslint-plugin-better-tailwindcss: ^4.6.1
    eslint-plugin-format: ~2.0.1
    eslint-plugin-vue: ^10.9.2
    mdclint: ^0.1.2
    vue-eslint-parser: ^10.4.1
  nuxt:
    '@nuxt/devtools': ^3.2.4
    '@nuxt/kit': ^4.4.8
    '@nuxt/schema': ^4.4.8
    '@nuxt/test-utils': ^4.0.3
    defu: ^6.1.7
    exsolve: ^1.1.0
    nuxt: ^4.4.8
    unimport: ^6.3.0
  release:
    changelogen: ^0.6.2
  test:
    vitest: ^4.1.9
  typescript:
    '@types/node': ^26.1.0
    typescript: ~6.0.3
    vue-tsc: ^3.3.6
  vue:
    tailwindcss: ^4.3.2
