import type { Nuxt } from '@nuxt/schema'
import type { Unimport } from 'unimport'
import type { NustackContext } from './context'
import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { resolveAlias } from '@nuxt/kit'

const TAILWIND_IMPORT_RE = /@import\s+["']tailwindcss["']/

/** Module name → context flag. Detected from the resolved module registry. */
const MODULE_FLAGS = {
  '@nuxt/ui': 'nuxtUi',
  '@nuxt/ui-pro': 'nuxtUi',
  '@pinia/nuxt': 'pinia',
  '@nuxt/image': 'nuxtImage',
  '@nuxt/content': 'nuxtContent',
  '@comark/nuxt': 'mdc',
  '@nuxtjs/mdc': 'mdc',
} as const satisfies Record<string, keyof NustackContext['modules']>

interface NitroWithUnimport {
  unimport?: Unimport
}

type NitroInitHook = (name: 'nitro:init', fn: (nitro: NitroWithUnimport) => void) => void

/**
 * Registers the hooks that observe the resolved Nuxt context and writes
 * `.nuxt/nustack-eslint.mjs` whenever the app is (re)generated, so the ESLint
 * config factory always reads a context that matches the real project.
 */
export function setupNustackContext(nuxt: Nuxt): void {
  let unimport: Unimport | undefined
  let nitroUnimport: Unimport | undefined
  let components: string[] = []

  nuxt.hook('imports:context', (ctx) => {
    unimport = ctx
  })
  ;(nuxt.hook as unknown as NitroInitHook)('nitro:init', (nitro) => {
    nitroUnimport = nitro.unimport
  })
  nuxt.hook('components:extend', (list) => {
    components = [...new Set(list.map(c => c.pascalName))].sort()
  })

  async function collectAutoImports(): Promise<string[]> {
    const imports = [
      ...await unimport?.getImports() ?? [],
      ...await nitroUnimport?.getImports() ?? [],
    ]
    const names = imports
      .filter(i => !i.type) // skip type-only imports
      .map(i => i.as || i.name)
      .filter((name): name is string => Boolean(name))
    return [...new Set(names)].sort()
  }

  function detectModules(): NustackContext['modules'] {
    const installed = new Set<string>()
    for (const m of nuxt.options._installedModules ?? []) {
      const name = m.meta?.name
      if (name)
        installed.add(name)
    }
    for (const m of nuxt.options.modules ?? []) {
      if (typeof m === 'string')
        installed.add(m)
    }

    const modules: NustackContext['modules'] = {
      nuxtUi: false,
      pinia: false,
      nuxtImage: false,
      nuxtContent: false,
      mdc: false,
    }
    for (const [name, flag] of Object.entries(MODULE_FLAGS)) {
      if (installed.has(name))
        modules[flag] = true
    }
    if (installed.has('@nuxt/content'))
      modules.mdc = true
    return modules
  }

  async function detectTailwind(): Promise<NustackContext['tailwind']> {
    for (const entry of nuxt.options.css ?? []) {
      if (typeof entry !== 'string' || !entry.endsWith('.css'))
        continue
      const abs = resolveAlias(entry, nuxt.options.alias)
      if (!existsSync(abs))
        continue
      try {
        const source = await readFile(abs, 'utf-8')
        if (TAILWIND_IMPORT_RE.test(source)) {
          return {
            detected: true,
            // better-tailwindcss resolves `entryPoint` relative to the lint cwd
            // (the project root), so store it relative to rootDir.
            entryPoint: relative(nuxt.options.rootDir, abs),
          }
        }
      } catch {
        // unreadable css entry — ignore and keep scanning
      }
    }
    return { detected: false, entryPoint: null }
  }

  async function buildContext(): Promise<NustackContext> {
    return {
      modules: detectModules(),
      tailwind: await detectTailwind(),
      autoImports: await collectAutoImports(),
      components,
    }
  }

  async function writeContextFile(): Promise<void> {
    const context = await buildContext()
    const file = join(nuxt.options.buildDir, 'nustack-eslint.mjs')
    await mkdir(dirname(file), { recursive: true })
    await writeFile(file, generateCode(context), 'utf-8')
  }

  // `builder:generateApp` runs on `nuxt prepare`, dev and build — after the
  // imports/components registries are populated.
  nuxt.hook('builder:generateApp', writeContextFile)
}

/** Serializes the resolved context into the generated ESM module. */
export function generateCode(context: NustackContext): string {
  return [
    '// Generated by @nustackjs/lint — do not edit.',
    '// Regenerated on every `nuxt prepare`.',
    `import { applyNustackConfig as factory } from '@nustackjs/lint/config'`,
    `import withNuxt from './eslint.config.mjs'`,
    '',
    `export const nustackContext = ${JSON.stringify(context, null, 2)}`,
    '',
    '/**',
    ' * Project-aware ESLint config, with `withNuxt()` already wired in. Pass one',
    ' * options object, then optional flat config objects. Returns the composer, so',
    ' * you can chain `.append()` / `.override()` / `.remove()` as an escape hatch.',
    ' */',
    'export function nustack(options = {}, ...configs) {',
    '  return factory(withNuxt(), { ...options, context: nustackContext }, ...configs)',
    '}',
    '',
    'export const nustackLint = nustack',
    '',
    '// Default export = the ready-to-use config, so `export { default } from` works.',
    'export default nustack()',
    '',
  ].join('\n')
}
